name: "Hakan Bilen @ homepages.inf.ed.ac.uk"
url: http://homepages.inf.ed.ac.uk
baseurl: /hbilen
permalink: /:year/:month/:day/:title
timezone: Europe/London

navigation:
- text: About
  url: /index.html
- text: Vacancies 
  url: /vacancies/index.html
- text: Publications
  url: /publications/index.html

scholar:
  style: apa
  repository: assets/pdf
  bibliography_template: bibliography
